"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tokenSchema = exports.Token = exports.categorySchema = exports.Category = exports.userSchema = exports.User = exports.articleSchema = exports.Article = exports.journalSchema = exports.Journal = void 0;
const journal_model_1 = require("./journal.model");
Object.defineProperty(exports, "Journal", { enumerable: true, get: function () { return journal_model_1.Journal; } });
Object.defineProperty(exports, "journalSchema", { enumerable: true, get: function () { return journal_model_1.journalSchema; } });
const article_model_1 = require("./article.model");
Object.defineProperty(exports, "Article", { enumerable: true, get: function () { return article_model_1.Article; } });
Object.defineProperty(exports, "articleSchema", { enumerable: true, get: function () { return article_model_1.articleSchema; } });
const user_model_1 = require("./user.model");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_model_1.User; } });
Object.defineProperty(exports, "userSchema", { enumerable: true, get: function () { return user_model_1.userSchema; } });
const category_model_1 = require("./category.model");
Object.defineProperty(exports, "Category", { enumerable: true, get: function () { return category_model_1.Category; } });
Object.defineProperty(exports, "categorySchema", { enumerable: true, get: function () { return category_model_1.categorySchema; } });
const token_model_1 = require("./token.model");
Object.defineProperty(exports, "Token", { enumerable: true, get: function () { return token_model_1.Token; } });
Object.defineProperty(exports, "tokenSchema", { enumerable: true, get: function () { return token_model_1.tokenSchema; } });
